
version: '3'

services:
  mfa-facade:
    image: ${DOCKER_USER}/nginx:${BUILD_VERSION}
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/reverse-proxy
    ports:
      - '8082:3000'
    extra_hosts:
      - "service.localhost:192.168.41.33"
  broker:
    image: ${DOCKER_USER}/broker:${BUILD_VERSION}
    build:
      dockerfile: Dockerfile
      context: ./services/broker
    ports:
      - '5672:5672'
      - '15674:15674'
      - '15672:15672'
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./data/logs:/var/log/rabbitmq
    hostname: rabbit
  eventstore:
    image: ${DOCKER_USER}/eventstore:${BUILD_VERSION}
    build:
      dockerfile: Dockerfile
      context: ./services/eventstore
    ports:
      - "1113:1113"
      - "2113:2113"
  simpleweb:
    image: ${DOCKER_USER}/simpleweb:${BUILD_VERSION}
    build:
      dockerfile: Dockerfile
      context: ./servers/node/simpleweb
    command: npm run dev:watch
    environment:
      SIMPLE_WEB_PORT: ${SIMPLE_WEB_PORT}
    ports:
      - "${SIMPLE_WEB_PORT}:${SIMPLE_WEB_PORT}"
    volumes: 
      - ./servers/node/simpleweb:/usr/app
      - nodemodules:/usr/app/node_modules
volumes:
    nodemodules: {}