
version: '3'

services:
  nginx:
    image: ${DOCKER_USER}/nginx:${BUILD_VERSION}
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/reverse-proxy
    ports:
      - '8082:3000'
    extra_hosts:
      - "service.localhost:192.168.41.33"

  # Proxies requests to internal services
  # reverse-proxy:
  #   image: nginx:1.17.10
  #   container_name: reverse_proxy_demo # ??
  #   depends_on:
  #       - weather-report
  #   volumes:
  #     - ./reverse_proxy/conf/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80

  # generates weather reports
  # weather-report:
  #   image: weather-report
  #   container_name: weather-report
  #   build:
  #     context: ./weather_report
  #   depends_on:
  #       - temperature-service
  #       - precip-service
  #   ports:
  #     - 8080:80
  #   restart: on-failure