version: "3"

services:
  nginx:
    image: ${DOCKER_USER}/nginx:${BUILD_VERSION}
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/reverse-proxy
    ports:
      - "8082:3000"
    extra_hosts:
      - "service.localhost:192.168.41.33"
  broker:
    image: ${DOCKER_USER}/broker:${BUILD_VERSION}
    build:
      dockerfile: Dockerfile
      context: ./services/broker
    ports:
      - "5672:5672"
      - "15674:15674"
  eventstore:
    image: ${DOCKER_USER}/eventstore:${BUILD_VERSION}
    build:
      dockerfile: Dockerfile
      context: ./services/eventstore
    ports:
      - "1113:1113"
      - "2113:2113"
