version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
     - "27017:27017"
    restart: always
    volumes:
      - ./data:/data/db
        
  azure-storage:
    image: azure-storage
    build: 
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    env_file: 
      ./azure-storage/.env
    ports:
     - "4001:4001"
    restart: "no"
  
  rabbit:
    image: rabbitmq:3.8.5-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
      - ./video-streaming/videos:/usr/src/app/videos:z
    ports:
      - "4000:80"
    env_file: 
      ./video-streaming/.env
    restart: "no"

  history:
    image: history
    build: 
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
     - "4003:80"
    env_file:
      ./history/.env
    depends_on:
      - db
      - rabbit
    restart: "no"
